In [1]:
using Logging, LoggingExtras
using Tar
using DelimitedFiles
#using Distributed
using Rasters
#using DimensionalData
using NCDatasets

In [2]:
#import Pkg; Pkg.update("NCDatasets")

In [3]:
start_idx = "2250"  # this is string
stop_idx = "2251"
start_idx = parse(Int64, start_idx)
stop_idx = parse(Int64, stop_idx)

2251

In [20]:
DataDir = "/Users/jldechow/Documents/Projects/UNC/CoReSSD/fullData"
PrecipDir = DataDir
water_year = 16

files = (
    "$DataDir/WY$(water_year)/SCF.nc",
    "$DataDir/WY$(water_year)/SWE_tavg.nc",
    #"$DataDir/WY$(water_year)/precip_scalar.nc"
    )

PS = Raster("$PrecipDir/WY$(water_year)/precip_scalar.nc";  name=:precip_scalar, lazy=true)


11700×4200×1 Raster{Float32,3} precip_scalar with dimensions: 
  X Mapped{Float32} Float32[-168.995, -168.985, …, -52.015, -52.005] ForwardOrdered Irregular Points crs: EPSG mappedcrs: EPSG,
  Y Mapped{Float32} Float32[30.005, 30.015, …, 71.985, 71.995] ForwardOrdered Irregular Points crs: EPSG mappedcrs: EPSG,
  Ti Sampled{Dates.DateTime} Dates.DateTime[Dates.DateTime("2015-10-01T00:00:00")] ForwardOrdered Irregular Points
extent: Extent(X = (-168.995f0, -52.005f0), Y = (30.005f0, 71.995f0), Ti = (Dates.DateTime("2015-10-01T00:00:00"), Dates.DateTime("2015-10-01T00:00:00")))crs: EPSG:4326
mappedcrs: EPSG:4326
from file:
/Users/jldechow/Documents/Projects/UNC/CoReSSD/fullData/WY16/precip_scalar.nc

In [6]:
A = A[(:SWE_tavg, :SCF )]

RasterStack with dimensions: 
  X Mapped{Union{Missing, Float32}} Union{Missing, Float32}[-168.995, -168.985, …, -52.015, -52.005] ForwardOrdered Irregular Points crs: EPSG mappedcrs: EPSG,
  Y Mapped{Union{Missing, Float32}} Union{Missing, Float32}[30.005, 30.015, …, 71.985, 71.995] ForwardOrdered Irregular Points crs: EPSG mappedcrs: EPSG,
  Ti Sampled{Dates.DateTime} Dates.DateTime[2015-10-01T00:00:00, …, 2016-09-30T00:00:00] ForwardOrdered Irregular Points
and 2 layers:
  :SWE_tavg Union{Missing, UInt16} dims: X, Y, Ti (11700×4200×366)
  :SCF      Union{Missing, Float32} dims: X, Y, Ti (11700×4200×366)


In [7]:
szY = size(A, 2)  # get size in Y-dimension; here dim = 2
if stop_idx > szY
    stop_idx = szY
end
szY

4200

In [8]:
A = A[X(1:end), Y(start_idx:stop_idx)]
PS  = PS[X(1:end), Y(start_idx:stop_idx)]

11700×2×1 Raster{Float32,3} precip_scalar with dimensions: 
  X Mapped{Float32} Float32[-168.995, -168.985, …, -52.015, -52.005] ForwardOrdered Irregular Points crs: EPSG mappedcrs: EPSG,
  Y Mapped{Float32} Float32[52.495f0, 52.505f0] ForwardOrdered Irregular Points crs: EPSG mappedcrs: EPSG,
  Ti Sampled{Dates.DateTime} Dates.DateTime[Dates.DateTime("2015-10-01T00:00:00")] ForwardOrdered Irregular Points
extent: Extent(X = (-168.995f0, -52.005f0), Y = (52.495f0, 52.505f0), Ti = (Dates.DateTime("2015-10-01T00:00:00"), Dates.DateTime("2015-10-01T00:00:00")))crs: EPSG:4326
mappedcrs: EPSG:4326
parent:
[:, :, 1]
            52.495   52.505
 -168.995  NaN      NaN
 -168.985  NaN      NaN
 -168.975  NaN      NaN
 -168.965  NaN      NaN
 -168.955  NaN      NaN
 -168.945  NaN      NaN
 -168.935  NaN      NaN
    ⋮               
  -52.075  NaN      NaN
  -52.065  NaN      NaN
  -52.055  NaN      NaN
  -52.045  NaN      NaN
  -52.035  NaN      NaN
  -52.025  NaN      NaN
  -52.015  NaN      N

In [9]:
# r2d can be X×Y or X×Y×1
nDayFix = size(A[:SWE_tavg], 3) 
PS_T = ndims(PS) == 2 ? reshape(PS, size(PS,1), size(PS,2), 1) : PS
PS_T = repeat(PS_T, 1, 1, nDayFix)  # X×Y×nt

11700×2×366 Array{Float32, 3}:
[:, :, 1] =
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
   ⋮  
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN

[:, :, 2] =
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
   ⋮  
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN

[:, :, 3] =
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
   ⋮  
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN

;;; … 

[:, :, 364] =
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
 NaN  NaN
   ⋮  


In [10]:
# --- helpers (paste once) ---

time_len(A; refvar::Symbol=:SWE_tavg) =
    hasdim(A[refvar], Ti) ? size(A[refvar], Ti) : 1

"""
Return per-pixel series for `var` at (i,j) from a Raster/RasterStack.
If its time length is 1, replicate to match `refvar`'s length (365/366).
`scale` applies a unit factor (e.g., 0.01).
"""
function pixel_series(src, var_or_none, i::Int, j::Int; refA=nothing, refvar::Symbol=:SWE_tavg, scale::Real=1)
    Nt = isnothing(refA) ? 1 : time_len(refA; refvar=refvar)
    r  = var_or_none === nothing ? src[X=i, Y=j] : src[var_or_none][X=i, Y=j]
    v  = Array(r)
    v  = isa(v, Number) ? [v] : v
    v  = (length(v) == 1 && Nt > 1) ? fill(v[1], Nt) : v
    return scale == 1 ? v : v .* scale
end
# --- end helpers ---

pixel_series

In [11]:
i = 8002; j = 1;


WRFSWE = A[:SWE_tavg][X=i, Y=j].data ./ 1000
#WRFP   = A[:Snowf_tavg][X=i, Y=j].data ./ 1000
#WRFG   = A[:Qg_tavg][X=i, Y=j].data
#AirT   = A[:Tair_f_tavg][X=i, Y=j].data ./ 100
MSCF   = A[:SCF][X=i, Y=j].data

# Get precip_scalar robustly (replicates to match SWE_tavg’s time length, incl. leap years)
PSval  = pixel_series(PS, nothing, i, j; refA=A, refvar=:SWE_tavg)  # no scale assumed

366-element Vector{Float32}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 ⋮
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

In [12]:
MSCF[183]

0.8344f0

In [13]:
PSval[183]

1.0f0

In [14]:
PS_T[i,j,1:nDayFix]

366-element Vector{Float32}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 ⋮
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

In [15]:
x = [ NaN 0 0 0 0 0 ]

1×6 Matrix{Float64}:
 NaN  0.0  0.0  0.0  0.0  0.0

In [16]:
isnan(first(x)) && (x .= 1)

1×6 Matrix{Float64}:
 1.0  1.0  1.0  1.0  1.0  1.0

In [17]:

isnan(first(x)) && (x .= 1)
# x == [1.0, 1.0, 1.0]


false

In [18]:
x = [NaN, 2, 3]
if isnan(first(x))
       x.=1;
end

3-element Vector{Float64}:
 1.0
 1.0
 1.0